---
version: "3.9"
services:
  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase-data
      - ./data:/data:ro
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db

